#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MonoDroid.Resource", IsApplication=true)]

namespace MonoDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fragment_trans_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fragment_trans_out = 2130968577;
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int style_bottom_tab_bar_item_text_color = 2131034112;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int style_bottom_tab_bar_item_drawable_padding = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int style_bottom_tab_bar_item_margin_top = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int style_bottom_tab_bar_item_padding_top = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int style_bottom_tab_text_size = 2131099649;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int image1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int image2 = 2130837506;
			
			// aapt resource value: 0x7f020004
			public const int style_bottom_tab_bar_background_color = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int style_bottom_tab_bar_item_background = 2130837509;
			
			// aapt resource value: 0x7f020003
			public const int style_bottom_tab_bar_item_background_selector = 2130837507;
			
			// aapt resource value: 0x7f020006
			public const int style_bottom_tab_bar_item_checked_background = 2130837510;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0001
			public const int activity_actionbarmenu_textview = 2131361793;
			
			// aapt resource value: 0x7f0a0017
			public const int activity_main_list_item_imageview = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int activity_main_list_item_textview = 2131361816;
			
			// aapt resource value: 0x7f0a0012
			public const int edit_name = 2131361810;
			
			// aapt resource value: 0x7f0a0000
			public const int fragment_actionbar_tabs_viewpager = 2131361792;
			
			// aapt resource value: 0x7f0a0006
			public const int fragment_animations_layout_animation_button = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int fragment_animations_layout_animation_imageview = 2131361797;
			
			// aapt resource value: 0x7f0a0003
			public const int fragment_animations_layout_animation_linear_layout = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int fragment_animations_layout_animation_textview = 2131361796;
			
			// aapt resource value: 0x7f0a0007
			public const int fragment_animations_property_animation_seekbar1 = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int fragment_animations_property_animation_seekbar2 = 2131361800;
			
			// aapt resource value: 0x7f0a000a
			public const int fragment_animations_view_animation_button = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int fragment_animations_view_animation_imageView = 2131361801;
			
			// aapt resource value: 0x7f0a0002
			public const int fragment_animations_viewpager = 2131361794;
			
			// aapt resource value: 0x7f0a0011
			public const int fragment_collection_demo_pager_itle_strip = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int fragment_collection_demo_viewpager = 2131361808;
			
			// aapt resource value: 0x7f0a0013
			public const int fragment_dialog_test_button_show = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int fragment_dialog_test_popup_edit_name = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int fragment_dialog_test_popup_lbl_your_name = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int fragment_dialog_test_popup_txt_your_name = 2131361814;
			
			// aapt resource value: 0x7f0a001a
			public const int fragment_navigation_button = 2131361818;
			
			// aapt resource value: 0x7f0a0019
			public const int fragment_navigation_edittext = 2131361817;
			
			// aapt resource value: 0x7f0a001b
			public const int fragment_navigation_target_textview = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int fragment_pager_tabstrip_viewpager = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int fragment_pagertabstrip_tabstrip = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int fragment_popup_menu_button = 2131361822;
			
			// aapt resource value: 0x7f0a000b
			public const int frameLayout1 = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int radioButton1 = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int radioButton2 = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int radioButton3 = 2131361807;
			
			// aapt resource value: 0x7f0a000c
			public const int radioGroup1 = 2131361804;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_gesture = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_actionbar_tabs = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_actionbar_tabs_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_actionbarmenu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_animations = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_animations_layout_animation = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_animations_property_animation = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int fragment_animations_view_animation = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int fragment_bottom_tabbar = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int fragment_collection_demo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int fragment_collection_object = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int fragment_dialog_test = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int fragment_dialog_test_popup = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int fragment_menu_list_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int fragment_navigation = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int fragment_navigation_target = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int fragment_pager_tabstrip_tabs = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int fragment_popup_menu = 2130903057;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int fragment_actionbarmenu_menu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int fragment_popup_menu_popup = 2131296257;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int fragment_navigation_button_text = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int fragment_navigation_edittext_hint = 2131165185;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int bottom_tab_bar = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int bottom_tab_bar_item = 2131230721;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
